In [1]:
import pandas as pd

df = pd.read_csv("Log of complaints.csv", encoding='windows-1252')

df.head()
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 16071 entries, 0 to 16070
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_at              16071 non-null  str
 1   ward_id                 16071 non-null  int64
 2   title                   16071 non-null  str
 3   description             16071 non-null  str
 4   sub_category_id         16071 non-null  int64
 5   civic_agency_id         15452 non-null  float64
 6   location                16071 non-null  str
 7   address                 8878 non-null   str
 8   latitude                16071 non-null  float64
 9   longitude               16071 non-null  float64
 10  ward_title              16039 non-null  str
 11  category_id             16039 non-null  float64
 12  category_title          16039 non-null  str
 13  sub_category_title      16053 non-null  str
 14  civic_agency_title      15416 non-null  str
 15  complaint_status_title  16071 non-null  str
 16  comment_count           16071 non-null  int64
dtypes: float64(4), int64(3), str(10)
memory usage: 2.1 MB

created_at                   0
ward_id                      0
title                        0
description                  0
sub_category_id              0
civic_agency_id            619
location                     0
address                   7193
latitude                     0
longitude                    0
ward_title                  32
category_id                 32
category_title              32
sub_category_title          18
civic_agency_title         655
complaint_status_title       0
comment_count                0
dtype: int64

In [3]:
# 1. Convert date
df['created_at'] = pd.to_datetime(df['created_at'], format='mixed')

# 2. Drop useless columns
df = df.drop(columns=[
    'title', 'description',
    'sub_category_id', 'category_id',
    'civic_agency_id'
])

# 3. Handle missing values

# Drop rows where critical info missing
df = df.dropna(subset=['ward_title', 'category_title'])

# Fill less important ones
df['civic_agency_title'] = df['civic_agency_title'].fillna('Unknown')

# Drop address (too many missing)
df = df.drop(columns=['address'])

df.head()

,created_at,ward_id,location,latitude,longitude,ward_title,category_title,sub_category_title,civic_agency_title,complaint_status_title,comment_count
0,2019-01-01 06:33:00,22,"9Th Cross St, Hanumanthappa Layout, Sultanpaly...",13.031806,77.605437,Vishwanath Nagenahalli,Community Infrastructure and Services,Government Land/Property Encroachment,BBMP,Resolved,6
1,2019-01-01 09:59:00,27,"2, 1St Cross Rd, Chikka Banaswadi, Ombr Layout...",13.006506,77.644485,Banasavadi,Others,Others,Unknown,Open,0
2,2019-01-01 12:57:00,17,"No.18 19Th Cross, 19, 19Th Cross, Muthyala Nag...",13.038634,77.551505,J P Park,Certificates,Property Tax,BBMP,Resolved,1
3,2019-01-01 13:09:00,161,"Anjaneya Nagar, Ittamadu, Banashankari 3Rd Sta...",12.926871,77.544714,Hosakerehalli,"Mobility - Roads, Footpaths and Infrastructure",Tarring Or Asphalting Of Existing Road,BBMP,Resolved,2
4,2019-01-01 14:41:00,176,"27Th Main Rd, Btm 2Nd Stage, Kuvempu Nagar, St...",12.913905,77.614249,BTM Layout,Water Supply and Services,Regular Water Supply,BWSSB,Open,0

In [4]:
df.shape

(16039, 11)

In [5]:
df['category_title'].value_counts()

category_title
Mobility - Roads, Footpaths and Infrastructure               5072
Garbage and Unsanitary Practices                             3946
Traffic and Road Safety                                       967
Yellow Spot                                                   948
Animal Husbandry                                              859
Street lighting                                               807
Streetlights                                                  693
Pollution                                                     437
Others                                                        346
Water Supply and Services                                     320
Sewerage Systems                                              301
Electricity and Power Supply                                  228
Crime and Safety                                              143
Storm Water Drains                                            138
Community Infrastructure and Services                         133
Parks & Recreation                                            121
Roads and Footpaths                                           113
Trees and Saplings                                            104
Public Toilets                                                 61
Lakes                                                          54
Certificates                                                   53
Sanitation                                                     39
Public Transport - BMTC                                        35
Water Supply                                                   21
Mobility - Roads, Public transport                             19
Covid 19                                                       11
Safety and Crime                                               11
Fire Safety                                                    10
Electricity & Power                                             8
Public transport (BMTC and Metro)                               7
Playgrounds                                                     7
PWD                                                             5
Solid Waste Management                                          5
Power supply                                                    5
Public Transport - KSRTC                                        4
Pension                                                         1
EMP Grievance Redressal                                         1
Ration Card                                                     1
Fire Pollution                                                  1
Animal Catcher                                                  1
Proibition & Sale of Tobacco products, Plastic carry bags       1
Parks & Garden                                                  1
Waste Management                                                1
Name: count, dtype: int64

In [6]:
df['category_title'] = df['category_title'].replace({
    'Streetlights': 'Street lighting',
    'Roads and Footpaths': 'Mobility - Roads, Footpaths and Infrastructure',
    'Mobility - Roads, Public transport': 'Mobility - Roads, Footpaths and Infrastructure',
    'Water Supply': 'Water Supply and Services',
    'Electricity & Power': 'Electricity and Power Supply',
    'Power supply': 'Electricity and Power Supply',
    'Solid Waste Management': 'Garbage and Unsanitary Practices',
    'Waste Management': 'Garbage and Unsanitary Practices'
})

In [7]:
df['category_title'].value_counts()

category_title
Mobility - Roads, Footpaths and Infrastructure               5204
Garbage and Unsanitary Practices                             3952
Street lighting                                              1500
Traffic and Road Safety                                       967
Yellow Spot                                                   948
Animal Husbandry                                              859
Pollution                                                     437
Others                                                        346
Water Supply and Services                                     341
Sewerage Systems                                              301
Electricity and Power Supply                                  241
Crime and Safety                                              143
Storm Water Drains                                            138
Community Infrastructure and Services                         133
Parks & Recreation                                            121
Trees and Saplings                                            104
Public Toilets                                                 61
Lakes                                                          54
Certificates                                                   53
Sanitation                                                     39
Public Transport - BMTC                                        35
Covid 19                                                       11
Safety and Crime                                               11
Fire Safety                                                    10
Public transport (BMTC and Metro)                               7
Playgrounds                                                     7
PWD                                                             5
Public Transport - KSRTC                                        4
Pension                                                         1
EMP Grievance Redressal                                         1
Ration Card                                                     1
Fire Pollution                                                  1
Animal Catcher                                                  1
Proibition & Sale of Tobacco products, Plastic carry bags       1
Parks & Garden                                                  1
Name: count, dtype: int64

In [8]:
df['year'] = df['created_at'].dt.year

df['year'].value_counts().sort_index()

year
2019    7383
2020    4476
2021    2632
2022    1548
Name: count, dtype: int64

In [9]:
df['month'] = df['created_at'].dt.to_period('M')

df['month'].value_counts().sort_index()

month
2019-01    443
2019-02    461
2019-03    613
2019-04    484
2019-05    590
2019-06    606
2019-07    639
2019-08    739
2019-09    683
2019-10    869
2019-11    801
2019-12    455
2020-01    578
2020-02    658
2020-03    571
2020-04    160
2020-05    246
2020-06    245
2020-07    179
2020-08    230
2020-09    271
2020-10    324
2020-11    289
2020-12    725
2021-01    612
2021-02    241
2021-03    227
2021-04    147
2021-05    106
2021-06    131
2021-07    193
2021-08    172
2021-09    176
2021-10    192
2021-11    259
2021-12    176
2022-01    169
2022-02    182
2022-03    340
2022-04    179
2022-05    207
2022-06    263
2022-07    208
Freq: M, Name: count, dtype: int64

In [10]:
df['ward_title'].value_counts().head(10)

ward_title
Bellanduru          727
Other               637
Begur               535
Horamavu            506
Thanisandra         364
Dodda Nekkundi      350
Varthur             324
HSR Layout          292
Singasandra         280
Ramamurthy Nagar    255
Name: count, dtype: int64

In [11]:
top_wards = df['ward_title'].value_counts().head(5).index

df[df['ward_title'].isin(top_wards)] \
    .groupby(['ward_title', 'category_title']) \
    .size() \
    .sort_values(ascending=False)

ward_title   category_title
Bellanduru   Mobility - Roads, Footpaths and Infrastructure    381
Other        Mobility - Roads, Footpaths and Infrastructure    283
Begur        Mobility - Roads, Footpaths and Infrastructure    280
Horamavu     Mobility - Roads, Footpaths and Infrastructure    234
Thanisandra  Mobility - Roads, Footpaths and Infrastructure    194
                                                              ...
Other        Public Transport - BMTC                             1
             Sanitation                                          1
             Public Transport - KSRTC                            1
             Storm Water Drains                                  1
Thanisandra  Crime and Safety                                    1
Length: 96, dtype: int64

In [12]:
top_wards = df[df['ward_title'] != 'Other']['ward_title'].value_counts().head(5).index

df[df['ward_title'].isin(top_wards)] \
    .groupby(['ward_title', 'category_title']) \
    .size() \
    .reset_index(name='count') \
    .sort_values(['ward_title', 'count'], ascending=[True, False])

     ward_title                                  category_title  count
8         Begur  Mobility - Roads, Footpaths and Infrastructure    280
7         Begur                Garbage and Unsanitary Practices     79
17        Begur                                 Street lighting     51
0         Begur                                Animal Husbandry     23
15        Begur                                Sewerage Systems     15
..          ...                                             ...    ...
87  Thanisandra                         Public Transport - BMTC      3
80  Thanisandra           Community Infrastructure and Services      2
89  Thanisandra                              Storm Water Drains      2
92  Thanisandra                              Trees and Saplings      2
81  Thanisandra                                Crime and Safety      1

[95 rows x 3 columns]

In [13]:
df['complaint_status_title'].value_counts(normalize=True) * 100

complaint_status_title
Open          54.897437
Resolved      30.762516
On-the-Job    10.306129
Re-opened      2.069954
Rejected       1.265665
Closed         0.698298
Name: proportion, dtype: float64